extra-experimental-features = nix-command flakes
# is there a way to get the current flake name for inclusion here?
# would we want that?
# we could use a shell hook instead?
bash-prompt-suffix = +nix>$' '
